humhub/polls

- models/Poll.php
Cought an exception:
yii\base\ErrorException: Trying to get property of non-object in ..humhub/protected/modules/polls/models/Poll.php:257
> exception handling

- messages/zh_cn/base.php
- messages/zh_cn/controllers_PollController.php
- messages/zh_cn/events.php
- messages/zh_cn/views_activities_PollAnswered.php
- messages/zh_cn/widgets_views_entry.php
- messages/zh_cn/widgets_views_pollForm.php
- messages/zh_cn/widgets_views_stream.php
> update zh_cn language

- docs/CHANGELOG.md
- permissions/CreatePoll.php
> Fix #77 make permission settings translatable

- activities/NewVote.php
- docs/CHANGELOG.md
Issue: https://github.com/humhub/humhub-modules-polls/issues/80
> Exclude from Mail Summary (Activity)

- Events.php
- docs/CHANGELOG.md
Issue: https://github.com/humhub/humhub-modules-polls/issues/82
> Fix install sample content

- Events.php
- docs/CHANGELOG.md
Issue: https://github.com/humhub/humhub/issues/4558
> Deprecate CompatModuleManager

- Events.php
- docs/CHANGELOG.md
[fixed] access user by usernames instead of ids
humhub/team_tasks#71
> fixed tests for galera compatibility

- Events.php
- docs/CHANGELOG.md
Issue: https://github.com/humhub/polls/issues/96
> Change icon in sidebar menu

- Module.php
- docs/CHANGELOG.md
Issue: https://github.com/humhub/polls/issues/102
> Fix yii console Help without installed Rest module

- docs/CHANGELOG.md
- module.json
- widgets/WallCreateForm.php
- widgets/views/form.php
Issue: https://github.com/humhub/team_tasks/issues/238
> Remove deprecated checkbox "regular" style

- docs/CHANGELOG.md
- models/Poll.php
Issue: https://github.com/humhub/polls/issues/107
> Make field "Question" mandatory

- widgets/views/form.php
Issue: https://github.com/humhub/team_tasks/issues/261
> Improve styles of wall entry create form

- models/Poll.php
- tests/codeception/acceptance/PollCest.php
Issue: https://github.com/humhub/graphic-issues/issues/6
> Update wording and icon

- docs/CHANGELOG.md
- models/PollAnswer.php
- models/PollAnswerUser.php
- module.json
- tests/codeception/acceptance/PollCest.php
- widgets/views/_answer.php
Issue: https://github.com/humhub/polls/issues/117
> Fix responsive layout bug

- docs/CHANGELOG.md
- models/Poll.php
- module.json
Issue: https://github.com/humhub/humhub/issues/6344
> Fix double insertion of answers

- config.php
- docs/CHANGELOG.md
https://github.com/humhub/team_tasks/issues/321
> Remove unused events from config

- docs/README.md
Making it consistent with other new module descriptions.
> Fixing Docs

- docs/CHANGELOG.md
- widgets/views/_answer.php
https://github.com/humhub/humhub-internal/issues/282
> Fix wall stream horizontally scrollable

- Module.php
@yurabakhtin I don't want to bother you, but could you please check this one? :D
Issue: https://github.com/humhub/humhub-internal/issues/300#issuecomment-2194923277
> Resources dir fix

- messages/pt-BR/base.php
https://github.com/humhub/polls/issues/139
> Add translation for number of votes

- docs/CHANGELOG.md
- models/Poll.php
https://github.com/humhub/humhub-internal/issues/1
> Enable the feature to move a content to another space

- docs/CHANGELOG.md
- extensions/custom_pages/elements/PollElement.php
- module.json
https://github.com/humhub/custom-pages-internal/issues/87
> Use content ID in the "Custom Pages" extension

- extensions/custom_pages/elements/PollElementVariable.php
https://github.com/humhub/custom-pages-internal/issues/103
> Fix extension for module "Custom Pages"
